'use client';

import { useEffect, useRef, useState } from 'react';
import { api, dateLabel, employeePath, jsonPost, message, percent } from '../lib/api';
import { statusLabels, type Activity, type Page, type Completion, type Employee, type Event, type Recommendation, type Skill, type Trajectory } from '../lib/contracts';
import { ErrorNotice, Loading, useResource } from './workspace';

function Readiness({ value }: { value: number | null }) {
  return <div className="cq-readiness"><strong>{percent(value)}</strong><span>готовность к следующему грейду</span>{value !== null && <progress max={100} value={value} aria-label="Готовность к следующему грейду" />}</div>;
}

function SkillTable({ skills }: { skills: Skill[] }) {
  return skills.length ? <div className="cq-skill-list">{skills.map(skill => <div className="cq-skill" key={skill.skill_id}><div><strong>{skill.name}</strong>{skill.critical && <span className="cq-tag amber">Ключевой навык</span>}<small>{skill.required_level === null ? 'Требование не задано' : `Требование: ${skill.required_level} / 5`}</small></div><div><strong>{skill.current_level} <span className="cq-muted">/ 5</span></strong><progress max={5} value={skill.current_level} aria-label={`${skill.name}: ${skill.current_level} из 5`} /></div></div>)}</div> : <p className="cq-empty">Навыков для отображения пока нет.</p>;
}

function ActivityDetails({ recommendation, employeeId, readOnly, onClose, onComplete }: { recommendation: Recommendation; employeeId: string; readOnly: boolean; onClose: () => void; onComplete: (result: Completion) => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const busyRef = useRef(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const event = useResource<Event>(`events/${encodeURIComponent(recommendation.event_id)}`);
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    const element = dialog.current;
    element?.showModal();
    return () => { element?.close(); previous?.focus(); };
  }, []);
  async function complete() {
    if (busyRef.current) return;
    busyRef.current = true; setBusy(true); setError('');
    try {
      const result = await api<Completion>(`${employeePath(employeeId)}/activities/${encodeURIComponent(recommendation.event_id)}/complete`, jsonPost({}));
      onComplete(result);
    } catch (error) { setError(message(error)); }
    finally { busyRef.current = false; setBusy(false); }
  }
  return <dialog className="cq-dialog" ref={dialog} aria-labelledby="activity-title" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }}><div className="cq-dialog-content"><div className="cq-section-heading"><span className="cq-kicker">СЛЕДУЮЩИЙ ШАГ</span><button className="outline-button" onClick={onClose} disabled={busy} autoFocus>Закрыть</button></div><h2 id="activity-title">{recommendation.title}</h2>{event.loading ? <Loading /> : event.error ? <ErrorNotice error={event.error} retry={event.retry} /> : event.data && <><p>{event.data.description}</p><p className="cq-muted">{event.data.type}{event.data.duration_hours != null && ` · ${event.data.duration_hours} ч`}</p><h3>Что развивает активность</h3><ul className="cq-effects">{event.data.develops_skills.map(skill => <li key={skill.skill_id}><strong>{skill.name}</strong><span>Прирост: +{skill.gain} · предел: {skill.max_level} / 5</span></li>)}</ul></>}<div className="cq-reason"><h3>Почему этот шаг</h3><p>{recommendation.reason}</p></div><h3>Ожидаемый результат</h3><ul className="cq-effects">{recommendation.skills.map(skill => <li key={skill.skill_id}><strong>{skill.name}: {skill.current_level} → {skill.predicted_level}</strong><span>Требование целевого грейда: {skill.required_level ?? 'не задано'}</span></li>)}</ul><p>Ожидаемая готовность: <strong>{percent(recommendation.career_readiness_before)} → {percent(recommendation.career_readiness_after)}</strong></p>{error && <ErrorNotice error={error} />}{readOnly ? <p className="cq-caption">Завершить активность можно в сессии сотрудника.</p> : <><p className="cq-caption">Отмечайте выполнение после прохождения активности. Изменения навыков сохранит сервер.</p><button className="primary-button" disabled={busy || !event.data} onClick={complete}>{busy ? 'Сохраняем результат…' : 'Отметить выполненной'}</button></>}</div></dialog>;
}

export function EmployeeProfile({ employeeId, readOnly = false }: { employeeId: string; readOnly?: boolean }) {
  const [revision, setRevision] = useState(0);
  const [historyOffset, setHistoryOffset] = useState(0);
  const [selected, setSelected] = useState<Recommendation | null>(null);
  const [completed, setCompleted] = useState<Completion | null>(null);
  const base = employeePath(employeeId);
  const profile = useResource<Employee>(base, revision);
  const trajectory = useResource<Trajectory>(`${base}/trajectory`, revision);
  const skills = useResource<Skill[]>(`${base}/skills`, revision);
  const recommendations = useResource<Recommendation[]>(`${base}/recommendations`, revision, true);
  const history = useResource<Page<Activity>>(`${base}/activities?limit=50&offset=${historyOffset}`, revision);
  return <div className="cq-stack">{completed && <section className="cq-notice success" role="status"><h2>{completed.already_completed ? 'Выполнение уже учтено' : 'Ещё один шаг к цели!'}</h2>{completed.changes.length ? <ul>{completed.changes.map(change => <li key={change.skill_id}>{change.name}: <strong>{change.before} → {change.after}</strong></li>)}</ul> : <p>Уровни навыков не изменились.</p>}<p>Готовность: <strong>{percent(completed.career_readiness_before)} → {percent(completed.career_readiness_after)}</strong></p><button className="outline-button" onClick={() => setCompleted(null)}>Скрыть результат</button></section>}
    {profile.loading ? <Loading text="Загружаем профиль…" /> : profile.error ? <ErrorNotice error={profile.error} retry={profile.retry} /> : profile.data && <section className="cq-profile-hero"><div><span className="cq-kicker">{readOnly ? 'ПРОФИЛЬ СОТРУДНИКА' : 'МОЁ РАЗВИТИЕ'} · {profile.data.employee_id}</span><h1>{profile.data.full_name || profile.data.employee_id}</h1><p>{profile.data.role} · {profile.data.grade}{trajectory.data?.target_grade && ` → ${trajectory.data.target_grade}`}</p><span className="cq-hero-meta">Стаж: {profile.data.tenure_months} мес.{profile.data.department && ` · ${profile.data.department}`}</span></div><Readiness value={trajectory.data ? trajectory.data.career_readiness : profile.data.career_readiness} /></section>}
    <div className="cq-profile-grid"><section className="surface-card"><div className="cq-section-heading"><div><span className="cq-kicker">ВАША ЦЕЛЬ</span><h2>Карьерная траектория</h2></div></div>{trajectory.loading ? <Loading /> : trajectory.error ? <ErrorNotice error={trajectory.error} retry={trajectory.retry} /> : trajectory.data && <><ol className="cq-path" aria-label="Карьерные грейды">{trajectory.data.grades.map(grade => <li key={grade} className={grade === trajectory.data!.current_grade ? 'current' : ''}><strong>{grade}</strong>{grade === trajectory.data!.current_grade ? <small>Сейчас</small> : grade === trajectory.data!.target_grade ? <small>Следующая цель</small> : null}</li>)}</ol><p className="cq-muted">{trajectory.data.target_grade ? `Требования: ${trajectory.data.target_role || profile.data?.role || ''} · ${trajectory.data.target_grade}` : 'Следующий грейд не задан. Можно продолжать развивать навыки в текущей роли.'}</p><SkillTable skills={trajectory.data.requirements} /></>}</section>
    <section className="surface-card"><span className="cq-kicker">ФОКУС РАЗВИТИЯ</span><h2>Ближе к следующему уровню</h2><p className="cq-muted">Разрывы между текущими навыками и требованиями вашей цели.</p>{trajectory.loading ? <Loading /> : trajectory.error ? <ErrorNotice error={trajectory.error} retry={trajectory.retry} /> : trajectory.data && <>{trajectory.data.requirements.filter(skill => skill.required_level !== null && skill.current_level < skill.required_level).map(skill => <div className="cq-gap" key={skill.skill_id}><div><strong>{skill.name}</strong>{skill.critical && <small>Ключевой для следующего грейда</small>}</div><span>{skill.current_level} / {skill.required_level}</span></div>)}{!trajectory.data.requirements.some(skill => skill.required_level !== null && skill.current_level < skill.required_level) && <p className="cq-empty">По заданным требованиям разрывов нет.</p>}</>}</section></div>
    <section aria-labelledby="recommendations-heading"><div className="cq-section-heading"><div><span className="cq-kicker">ПЕРСОНАЛЬНЫЙ ПЛАН</span><h2 id="recommendations-heading">Ваши следующие шаги</h2><p className="cq-muted">Рекомендации с учётом профиля, требований и истории участия.</p></div><button className="outline-button" disabled={recommendations.loading} onClick={recommendations.retry}>Обновить</button></div>{recommendations.loading ? <Loading text="Подбираем шаги развития…" /> : recommendations.error ? <ErrorNotice error={recommendations.error} retry={recommendations.retry} /> : recommendations.data && (recommendations.data.length ? <div className="cq-recommendations">{recommendations.data.map(rec => <article className="surface-card cq-recommendation" key={rec.event_id}><div className="cq-section-heading"><span className="cq-tag">Приоритет {rec.priority}</span><span className="cq-caption">{rec.explanation_source === 'ai' ? 'AI-объяснение' : 'Объяснение по фактам'}</span></div><h3>{rec.title}</h3><ul className="cq-effects">{rec.skills.map(skill => <li key={skill.skill_id}><strong>{skill.name}</strong><span>Сейчас {skill.current_level} / 5 · цель {skill.required_level ?? '—'} / 5</span><span>Прирост активности +{skill.gain} · ожидаемый уровень {skill.predicted_level} / 5</span></li>)}</ul><p className="cq-outcome">Готовность: <strong>{percent(rec.career_readiness_before)} → {percent(rec.career_readiness_after)}</strong></p><details className="cq-why"><summary>Почему рекомендовано?</summary><p>{rec.reason}</p></details><button className="primary-button" onClick={() => setSelected(rec)}>Подробнее об активности →</button></article>)}</div> : <div className="surface-card cq-empty"><h3>Подходящих шагов пока нет</h3><p>Сейчас нет доступных активностей, соответствующих профилю и цели.</p></div>)}</section>
    <section className="surface-card"><h2>Все навыки</h2>{skills.loading ? <Loading /> : skills.error ? <ErrorNotice error={skills.error} retry={skills.retry} /> : skills.data && <details><summary>Открыть навыки ({skills.data.length})</summary><SkillTable skills={skills.data} /></details>}</section>
    <section className="surface-card"><h2>История активностей</h2>{history.loading ? <Loading /> : history.error ? <ErrorNotice error={history.error} retry={history.retry} /> : history.data && (history.data.items.length ? <div className="cq-table-scroll"><table><caption className="sr-only">История участия сотрудника</caption><thead><tr><th>Активность</th><th>Статус</th><th>Дата</th></tr></thead><tbody>{history.data.items.map(activity => <tr key={activity.record_id}><td>{activity.title}</td><td><span className={`cq-tag ${activity.status === 'completed' ? '' : 'neutral'}`}>{statusLabels[activity.status] || activity.status}</span></td><td className="cq-nowrap">{dateLabel(activity.date)}</td></tr>)}</tbody></table></div> : <p className="cq-empty">История участия пока пуста.</p>)}{history.data && history.data.total > history.data.limit && <div className="cq-pagination"><button className="outline-button" disabled={historyOffset === 0} onClick={() => setHistoryOffset(value => Math.max(0, value - 50))}>← Назад</button><span>{history.data.offset + 1}–{history.data.offset + history.data.items.length} из {history.data.total}</span><button className="outline-button" disabled={historyOffset + history.data.limit >= history.data.total} onClick={() => setHistoryOffset(value => value + 50)}>Далее →</button></div>}</section>
    {selected && <ActivityDetails recommendation={selected} employeeId={employeeId} readOnly={readOnly} onClose={() => setSelected(null)} onComplete={result => { setCompleted(result); setSelected(null); setHistoryOffset(0); setRevision(value => value + 1); window.scrollTo({ top: 0, behavior: 'smooth' }); }} />}
  </div>;
}
